### ISSUE TITLE
Exact data of incidents not correctly reported

### ISSUE THREAD

**Issue by asrivasatava** [azsec/azure-sentinel-tools#1]
Hi,

I have tried using the script in my enviroment, however I have found out that the count of incidents exported via script doesn't match with that present in Azure Sentinel.

To be specific, if I run the report today (say: 28th May), I will not be getting the most recent data i.e. I will get the incident count till 26th May. Data for 27th and 28th May will not be present in the extracted report.

**Comment by azsec** [comment]
@asrivasatava  Thank you for reporting the issue. I will look into it and get back to you soon.

**Comment by azsec** [comment]
@asrivasatava  I have fixed the issue by adding `$icds = $response.value` before processing `nextLink` with **While** loop. Please let me know if you still encounter the issue.

Thank you very much for reporting.
