### ISSUE TITLE
Enabling the investigation feature on a custom incident created by API.

### ISSUE THREAD

**Issue by KalaiarasanC** [azsec/azure-sentinel-tools#3]
For now, with the available API options, we are able to create the incident on sentinel. it would be much helpful if we can enable the investigate option for the custom incident. by doing that I hope we can use the investigation graph.

Can you please add any document file which contains all the possible options/body parameters for the custom methods for reference?

for example: 
    How to add the Entities(User, host, IP, etc..) in the API params.

**Comment by azsec** [comment]
Hi @KalaiarasanC 

I think there are two things: **Alert** and **Incident**. An alert causes an incident. In some alert types such as **Suspicious Authentication Activity** or **Failed SSH Brute-force attack** there are built-in entities that Azure Security Center captures for you.

Nevertheless the Azure Sentinel Incident API doesn't have **Entities** field. Below is the supported incident object in a request body in a new Incident API (2020-01-01):

```
{
  "etag": "string",
  "properties": {
    "additionalData": {},
    "classification": "Undetermined",
    "classificationComment": "string",
    "classificationReason": "SuspiciousActivity",
    "description": "string",
    "firstActivityTimeUtc": "2020-07-17T22:45:20.898Z",
    "labels": [
      {
        "labelName": "string"
      }
    ],
    "lastActivityTimeUtc": "2020-07-17T22:45:20.898Z",
    "owner": {
      "email": "string",
      "assignedTo": "string",
      "objectId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "userPrincipalName": "string"
    },
    "severity": "High",
    "status": "New",
    "title": "string"
  }
}
```
Sample request URL:

```
https://management.azure.com/subscriptions/1c4f72bb-24df-44b5-ad81-47e51a7c8da2/resourceGroups/azsec-rg/providers/Microsoft.OperationalInsights/workspaces/azsec-workspace/providers/Microsoft.SecurityInsights/incidents/1c4f72bb-24df-44b5-ad81-47e51a7c8da2?api-version=2020-01-01
```

**Comment by KalaiarasanC** [comment]
Thank you so much @azsec.

let's hope it will be available in the future. so we can create an incident as native alert does.

**Comment by azsec** [comment]
> Thank you so much @azsec.
> 
> let's hope it will be available in the future. so we can create an incident as native alert does.

You could add custom entity as tag/label. Because not all alerts have Host entity (e.g. PaaS service alert) so I don't think the Incident will support such an entity.

**Comment by azsec** [comment]
If you want to use label, follow the format below

```
..
        "labels": [
          {
            "labelName": "label1",
            "labelType": "User"
          },
          {
            "labelName": "test",
            "labelType": "User"
          }
        ]
```

**Comment by azsec** [comment]
Use this script to create a new custom Microsoft Sentinel Incident with the latest stable API https://github.com/azsec/azure-sentinel-tools/blob/master/scripts/incidents/New-AzSentinelIncident.ps1
