### ISSUE TITLE
Resource Group not found error

### ISSUE THREAD

**Issue by siddeshn** [azsec/azure-sentinel-tools#5]
![image](https://user-images.githubusercontent.com/37383104/115433654-b3c9a080-a1ff-11eb-94d7-22c0f88183d0.png)
I am getting RG not found  error when i have entered the right RG name and i am in as  contributor for that RG

**Comment by siddeshn** [comment]
![image](https://user-images.githubusercontent.com/37383104/115433810-dcea3100-a1ff-11eb-8880-8f7883184ca9.png)

**Comment by azsec** [comment]
@siddeshn Did you specify the subscription (in `TargetSubscriptionId` parameter) where your Azure Sentinel Workspace was? From the error it looks like you didn't have permission on the target subscription. Could you please check?

**Comment by azsec** [comment]
Closed the issue. If you wish to open please create a new issue. 

Thank you for your collaboration!
